### ISSUE TITLE
Engenharia de Requisitos

### ISSUE THREAD

**Issue by JYOshiro** [JYOshiro/Source-Code-Inspection#1]
## **_Descrição da falha:_**
>  As máquinas mantêm uma soma   total da quantidade de dinheiro que coletou durante toda sua operação”. A   quantidade se refere à sessão do usuário ou a toda a “vida” da máquina?

## **_Classificação:_**
>  Defeitos de requisitos

## **_Tipo de Defeito:_**
> Ambiguidade

## **_Severidade:_**
> Alta

**Comment by PattyGiovedi** [comment]
Corrigido: As máquinas mantêm uma soma total da quantidade de dinheiro que coletou durante a sessão do usuário.
