### ISSUE TITLE
Erro em for do método Inserir de TicketMachine

### ISSUE THREAD

**Issue by PattyGiovedi** [JYOshiro/Source-Code-Inspection#17]
public void inserir(int quantia) throws PapelMoedaInvalidaException {
        boolean achou = false;
        for (int i = 0; i < papelMoeda.length && !achou; i++) {
            if (**papelMoeda[1]** == quantia) {
                achou = true;
            }

Apenas a posição 2 do vetor de papel moeda é verificado.

**Comment by JYOshiro** [comment]
Foi alterado if (papelMoeda[1] == quantia) para if (papelMoeda[i] == quantia) {
