### ISSUE TITLE
CSU02 – Solicitar bilhete

### ISSUE THREAD

**Issue by JYOshiro** [JYOshiro/Source-Code-Inspection#6]
## **_Descrição da falha:_**
>  "Um único bilhete de transporte é impresso." Se o cliente quiser mais bilhetes, terá de repetir este caso de uso?

## **_Classificação:_**
>  Defeitos de requisitos

## **_Tipo de Defeito:_**
> Omissão

**Comment by PattyGiovedi** [comment]
O caso de uso será repetido caso o cliente deseje mais bilhetes.
