### ISSUE TITLE
Tela principal 

### ISSUE THREAD

**Issue by JYOshiro** [JYOshiro/Source-Code-Inspection#8]
## **_Descrição da falha:_**
>  Botão “Emitir” – nome não remete à função do botão. "Emitir Bilhete" faz mais sentido.

## **_Classificação:_**
>  Defeitos de requisitos

## **_Tipo de Defeito:_**
> Ambiguidade

**Comment by PattyGiovedi** [comment]
Alterado em documentação e em código-fonte.
